#![cfg_attr(feature = "nightly", feature(error_in_core))]
#![cfg_attr(feature = "nightly", feature(panic_info_message))]
#![cfg_attr(not(test), no_std)]

//! Simple peripheral-level USB stack

pub mod class;
pub mod control;
pub mod descriptor;
pub mod device;
pub mod error;
pub mod setup;
pub mod traits;

pub use error::SmolError;
pub use error::SmolResult;

// TODO const template structs
pub const EP_MAX_ENDPOINTS: usize = 16;
pub const EP_MAX_PACKET_SIZE: usize = 512;

pub mod event {
    /// Interface events generated by the USB interface's interrupt handler.
    #[derive(Copy, Clone)]
    #[repr(u8)]
    pub enum UsbEvent {
        /// Received a USB bus reset
        BusReset = 10,

        /// Received a SETUP packet on USBx_EP_CONTROL
        ///
        /// Contents is (endpoint_number)
        ReceiveSetupPacket(u8) = 11,

        /// Received a data packet on USBx_EP_OUT
        ///
        /// Contents is (endpoint_number)
        ReceivePacket(u8) = 12,

        /// Send is complete on USBx_EP_IN
        ///!
        /// Contents is (endpoint_number)
        SendComplete(u8) = 13,
    }

    impl core::fmt::Debug for UsbEvent {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            match self {
                UsbEvent::BusReset => {
                    write!(f, "BusReset")
                }
                UsbEvent::ReceiveSetupPacket(endpoint) => {
                    write!(f, "ReceiveSetupPacket({})", endpoint)
                }
                UsbEvent::ReceivePacket(endpoint) => {
                    write!(f, "ReceivePacket({})", endpoint)
                }
                UsbEvent::SendComplete(endpoint) => {
                    write!(f, "SendComplete({})", endpoint)
                }
            }
        }
    }

    impl From<UsbEvent> for u8 {
        fn from(event: UsbEvent) -> u8 {
            match event {
                UsbEvent::BusReset => 10,
                UsbEvent::ReceiveSetupPacket(_) => 11,
                UsbEvent::ReceivePacket(_) => 12,
                UsbEvent::SendComplete(_) => 13,
            }
        }
    }
}
